// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    static class Vsix
    {
        public const string Id = "MFA20CC7-7C8E-4E41-B258-539C067E5649";
        public const string Name = "Open in Markdown Monster";
        public const string Description = "Open a file in Markdown Monster directly from Solution Explorer within Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, MarkdownMonster, Markdown Monster, Markdown";
    }
}
