// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    static class Vsix
    {
        public const string Id = "$gregt$ - guid";
        public const string Name = "Open in $gregt$";
        public const string Description = @"Open a file in $gregt$ directly from Solution Explorer within Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, $gregt$";
    }
}
